services:
  tg_messages.api:
    container_name: tg_messages.api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - tg_messages.db
    env_file:
      - .env
    restart: unless-stopped

  tg_messages.db:
    container_name: tg_messages.db
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - tg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    restart: unless-stopped

#  tg_messages.vector:
#    image: timberio/vector:latest-alpine
#    container_name: tg_messages.vector
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - ./vector.yaml:/etc/vector/vector.yaml
#    env_file:
#      - .env
#    restart: unless-stopped
#    depends_on:
#      - tg_messages.api

volumes:
  tg_data: